# Generated by Django 3.2.6 on 2022-04-12 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0026_auto_20220412_1043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Love_for_Clients5',
        ),
    ]
